ui
defaultCommitText
	^ 'Looks like you have selected an empty project that does not have any commits in the repository yet. Usually you would find information about the selected commit here.

To get started, please add a package to track in this project. You can do it from the menu of the Projects list at the top left, or from the menu of the Objects list at the bottom right of the Git Browser. Afterwards, press Commit.'