as yet unclassified
default

	^ CoAuthorList new
		addName: 'Björn Daase' email: 'bjoern.daase@student.hpi.de';
		addName: 'Elina Emsbach' email: 'elina.emsbach@student.hpi.de';
		addName: 'Leon Bein' email: 'leonbein@web.de';
		addName: 'Leon Matthes' email: 'leon@matthes.biz';
		addName: 'Maximilian Stiede' email: 'maximilian.stiede@student.hpi.de';
		addName: 'Tom Braun' email: 'brauntom2@t-online.de';
		yourself