name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        smalltalk: [ Squeak64-trunk, Squeak64-6.0, Squeak64-5.3, Squeak32-5.2 ]
        # Since Squot does not deal with platforms really,
        # only run the latest versions on Windows and macOS.
        include:
          - os: macos-latest
            smalltalk: Squeak64-trunk
          - os: windows-latest
            smalltalk: Squeak64-trunk
      fail-fast: false # Do not let failures on Squeak 5.2 stop other jobs.
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
